#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_DQUOTE = 1,
  anon_sym_BQUOTE = 2,
  anon_sym_BQUOTE2 = 3,
  anon_sym_BQUOTE_LBRACE = 4,
  anon_sym_RBRACE = 5,
  aux_sym_stx_line_token1 = 6,
  aux_sym_stx_dquo_token1 = 7,
  aux_sym_stx_bloc_token1 = 8,
  aux_sym_stx_word_token1 = 9,
  sym_id = 10,
  sym__space = 11,
  sym__linefeed = 12,
  sym_lparen = 13,
  sym_rparen = 14,
  sym_lbrace = 15,
  sym_lbracket = 16,
  sym_rbracket = 17,
  sym__indent = 18,
  sym__dedent = 19,
  sym__break = 20,
  sym__sentinel = 21,
  sym_program = 22,
  sym__expr3 = 23,
  sym__expr2 = 24,
  sym__expr1 = 25,
  sym__expri = 26,
  sym_apply3 = 27,
  sym_apply2 = 28,
  sym_apply1 = 29,
  sym_applyi = 30,
  sym__e = 31,
  sym_string = 32,
  sym__stx_words = 33,
  sym__stx_group = 34,
  sym_blockquoted = 35,
  sym_interpol8 = 36,
  sym__codeblock = 37,
  sym_stx_line = 38,
  sym_stx_dquo = 39,
  sym_stx_bloc = 40,
  sym_stx_word = 41,
  sym_linefeed = 42,
  sym__linesplit = 43,
  sym_rbrace = 44,
  aux_sym_string_repeat1 = 45,
  aux_sym_string_repeat2 = 46,
  aux_sym__stx_words_repeat1 = 47,
  aux_sym__stx_group_repeat1 = 48,
  aux_sym_blockquoted_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_BQUOTE2] = "` ",
  [anon_sym_BQUOTE_LBRACE] = "`{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_stx_line_token1] = "stx_line_token1",
  [aux_sym_stx_dquo_token1] = "stx_dquo_token1",
  [aux_sym_stx_bloc_token1] = "stx_bloc_token1",
  [aux_sym_stx_word_token1] = "stx_word_token1",
  [sym_id] = "id",
  [sym__space] = "_space",
  [sym__linefeed] = "_linefeed",
  [sym_lparen] = "lparen",
  [sym_rparen] = "rparen",
  [sym_lbrace] = "lbrace",
  [sym_lbracket] = "lbracket",
  [sym_rbracket] = "rbracket",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__break] = "_break",
  [sym__sentinel] = "_sentinel",
  [sym_program] = "program",
  [sym__expr3] = "_expr3",
  [sym__expr2] = "_expr2",
  [sym__expr1] = "_expr1",
  [sym__expri] = "_expri",
  [sym_apply3] = "apply3",
  [sym_apply2] = "apply2",
  [sym_apply1] = "apply1",
  [sym_applyi] = "applyi",
  [sym__e] = "_e",
  [sym_string] = "string",
  [sym__stx_words] = "_stx_words",
  [sym__stx_group] = "_stx_group",
  [sym_blockquoted] = "blockquoted",
  [sym_interpol8] = "interpol8",
  [sym__codeblock] = "_codeblock",
  [sym_stx_line] = "stx_line",
  [sym_stx_dquo] = "stx_dquo",
  [sym_stx_bloc] = "stx_bloc",
  [sym_stx_word] = "stx_word",
  [sym_linefeed] = "linefeed",
  [sym__linesplit] = "_linesplit",
  [sym_rbrace] = "rbrace",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym__stx_words_repeat1] = "_stx_words_repeat1",
  [aux_sym__stx_group_repeat1] = "_stx_group_repeat1",
  [aux_sym_blockquoted_repeat1] = "blockquoted_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_BQUOTE2] = anon_sym_BQUOTE2,
  [anon_sym_BQUOTE_LBRACE] = anon_sym_BQUOTE_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_stx_line_token1] = aux_sym_stx_line_token1,
  [aux_sym_stx_dquo_token1] = aux_sym_stx_dquo_token1,
  [aux_sym_stx_bloc_token1] = aux_sym_stx_bloc_token1,
  [aux_sym_stx_word_token1] = aux_sym_stx_word_token1,
  [sym_id] = sym_id,
  [sym__space] = sym__space,
  [sym__linefeed] = sym__linefeed,
  [sym_lparen] = sym_lparen,
  [sym_rparen] = sym_rparen,
  [sym_lbrace] = sym_lbrace,
  [sym_lbracket] = sym_lbracket,
  [sym_rbracket] = sym_rbracket,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__break] = sym__break,
  [sym__sentinel] = sym__sentinel,
  [sym_program] = sym_program,
  [sym__expr3] = sym__expr3,
  [sym__expr2] = sym__expr2,
  [sym__expr1] = sym__expr1,
  [sym__expri] = sym__expri,
  [sym_apply3] = sym_apply3,
  [sym_apply2] = sym_apply2,
  [sym_apply1] = sym_apply1,
  [sym_applyi] = sym_applyi,
  [sym__e] = sym__e,
  [sym_string] = sym_string,
  [sym__stx_words] = sym__stx_words,
  [sym__stx_group] = sym__stx_group,
  [sym_blockquoted] = sym_blockquoted,
  [sym_interpol8] = sym_interpol8,
  [sym__codeblock] = sym__codeblock,
  [sym_stx_line] = sym_stx_line,
  [sym_stx_dquo] = sym_stx_dquo,
  [sym_stx_bloc] = sym_stx_bloc,
  [sym_stx_word] = sym_stx_word,
  [sym_linefeed] = sym_linefeed,
  [sym__linesplit] = sym__linesplit,
  [sym_rbrace] = sym_rbrace,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym__stx_words_repeat1] = aux_sym__stx_words_repeat1,
  [aux_sym__stx_group_repeat1] = aux_sym__stx_group_repeat1,
  [aux_sym_blockquoted_repeat1] = aux_sym_blockquoted_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_stx_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stx_dquo_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stx_bloc_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stx_word_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__linefeed] = {
    .visible = false,
    .named = true,
  },
  [sym_lparen] = {
    .visible = true,
    .named = true,
  },
  [sym_rparen] = {
    .visible = true,
    .named = true,
  },
  [sym_lbrace] = {
    .visible = true,
    .named = true,
  },
  [sym_lbracket] = {
    .visible = true,
    .named = true,
  },
  [sym_rbracket] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__break] = {
    .visible = false,
    .named = true,
  },
  [sym__sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__expr3] = {
    .visible = false,
    .named = true,
  },
  [sym__expr2] = {
    .visible = false,
    .named = true,
  },
  [sym__expr1] = {
    .visible = false,
    .named = true,
  },
  [sym__expri] = {
    .visible = false,
    .named = true,
  },
  [sym_apply3] = {
    .visible = true,
    .named = true,
  },
  [sym_apply2] = {
    .visible = true,
    .named = true,
  },
  [sym_apply1] = {
    .visible = true,
    .named = true,
  },
  [sym_applyi] = {
    .visible = true,
    .named = true,
  },
  [sym__e] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__stx_words] = {
    .visible = false,
    .named = true,
  },
  [sym__stx_group] = {
    .visible = false,
    .named = true,
  },
  [sym_blockquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_interpol8] = {
    .visible = true,
    .named = true,
  },
  [sym__codeblock] = {
    .visible = false,
    .named = true,
  },
  [sym_stx_line] = {
    .visible = true,
    .named = true,
  },
  [sym_stx_dquo] = {
    .visible = true,
    .named = true,
  },
  [sym_stx_bloc] = {
    .visible = true,
    .named = true,
  },
  [sym_stx_word] = {
    .visible = true,
    .named = true,
  },
  [sym_linefeed] = {
    .visible = true,
    .named = true,
  },
  [sym__linesplit] = {
    .visible = false,
    .named = true,
  },
  [sym_rbrace] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__stx_words_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__stx_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blockquoted_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 11,
  [14] = 14,
  [15] = 10,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 14,
  [20] = 17,
  [21] = 9,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 22,
  [27] = 27,
  [28] = 22,
  [29] = 22,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 36,
  [41] = 31,
  [42] = 32,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 48,
  [50] = 50,
  [51] = 35,
  [52] = 37,
  [53] = 53,
  [54] = 37,
  [55] = 37,
  [56] = 56,
  [57] = 56,
  [58] = 58,
  [59] = 59,
  [60] = 35,
  [61] = 35,
  [62] = 58,
  [63] = 37,
  [64] = 64,
  [65] = 35,
  [66] = 66,
  [67] = 64,
  [68] = 33,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 38,
  [75] = 75,
  [76] = 76,
  [77] = 71,
  [78] = 30,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 81,
  [85] = 80,
  [86] = 83,
  [87] = 79,
  [88] = 88,
  [89] = 89,
  [90] = 82,
  [91] = 83,
  [92] = 83,
  [93] = 88,
  [94] = 83,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 97,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 97,
  [104] = 75,
  [105] = 69,
  [106] = 102,
  [107] = 107,
  [108] = 108,
  [109] = 97,
  [110] = 102,
  [111] = 108,
  [112] = 102,
  [113] = 97,
  [114] = 102,
  [115] = 115,
  [116] = 96,
  [117] = 117,
  [118] = 117,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 115,
  [124] = 124,
  [125] = 122,
  [126] = 120,
};

static inline bool aux_sym_stx_bloc_token1_character_set_1(int32_t c) {
  return (c < '['
    ? (c < '\r'
      ? (c < '\n'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c >= '(' && c <= ')')))
    : (c <= '[' || (c < '{'
      ? (c < '`'
        ? c == ']'
        : c <= '`')
      : (c <= '{' || c == '}'))));
}

static inline bool aux_sym_stx_word_token1_character_set_1(int32_t c) {
  return (c < ','
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '('
        ? c == ' '
        : c <= ')')))
    : (c <= ',' || (c < '`'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '`' || (c < '}'
        ? c == '{'
        : c <= '}')))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '`') ADVANCE(15);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '`') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '`') ADVANCE(13);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '}') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == '`') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BQUOTE2);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BQUOTE_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_stx_line_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_stx_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_stx_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_stx_dquo_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_stx_dquo_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_stx_bloc_token1);
      if (!aux_sym_stx_bloc_token1_character_set_1(lookahead)) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_stx_word_token1);
      if (!aux_sym_stx_word_token1_character_set_1(lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_id);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__linefeed);
      if (lookahead == '\t') ADVANCE(30);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_lparen);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_rparen);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_lbrace);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_lbracket);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_rbracket);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 2},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0, .external_lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0, .external_lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 3},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0, .external_lex_state = 4},
  [81] = {.lex_state = 0, .external_lex_state = 4},
  [82] = {.lex_state = 0, .external_lex_state = 4},
  [83] = {.lex_state = 0, .external_lex_state = 3},
  [84] = {.lex_state = 0, .external_lex_state = 5},
  [85] = {.lex_state = 0, .external_lex_state = 5},
  [86] = {.lex_state = 0, .external_lex_state = 3},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0, .external_lex_state = 5},
  [89] = {.lex_state = 0, .external_lex_state = 6},
  [90] = {.lex_state = 0, .external_lex_state = 5},
  [91] = {.lex_state = 0, .external_lex_state = 3},
  [92] = {.lex_state = 0, .external_lex_state = 3},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 0, .external_lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0, .external_lex_state = 7},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0, .external_lex_state = 4},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0, .external_lex_state = 6},
  [105] = {.lex_state = 0, .external_lex_state = 4},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0, .external_lex_state = 7},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0, .external_lex_state = 7},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0, .external_lex_state = 4},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0, .external_lex_state = 7},
  [119] = {.lex_state = 0, .external_lex_state = 7},
  [120] = {.lex_state = 0, .external_lex_state = 4},
  [121] = {.lex_state = 0, .external_lex_state = 4},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0, .external_lex_state = 4},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0, .external_lex_state = 7},
  [126] = {.lex_state = 0, .external_lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE2] = ACTIONS(1),
    [anon_sym_BQUOTE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [sym__linefeed] = ACTIONS(1),
    [sym_lparen] = ACTIONS(1),
    [sym_rparen] = ACTIONS(1),
    [sym_lbrace] = ACTIONS(1),
    [sym_lbracket] = ACTIONS(1),
    [sym_rbracket] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__break] = ACTIONS(1),
    [sym__sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(124),
    [sym__expr3] = STATE(122),
    [sym__expr2] = STATE(82),
    [sym__expr1] = STATE(82),
    [sym_apply3] = STATE(122),
    [sym_apply2] = STATE(82),
    [sym_apply1] = STATE(82),
    [sym__e] = STATE(79),
    [sym_string] = STATE(79),
    [anon_sym_DQUOTE] = ACTIONS(3),
    [anon_sym_BQUOTE] = ACTIONS(5),
    [anon_sym_BQUOTE2] = ACTIONS(7),
    [sym_id] = ACTIONS(9),
    [sym__linefeed] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(13), 1,
      sym_id,
    ACTIONS(15), 1,
      sym__linefeed,
    STATE(119), 1,
      sym_program,
    STATE(87), 2,
      sym__e,
      sym_string,
    STATE(125), 2,
      sym__expr3,
      sym_apply3,
    STATE(90), 4,
      sym__expr2,
      sym__expr1,
      sym_apply2,
      sym_apply1,
  [33] = 8,
    ACTIONS(17), 1,
      anon_sym_BQUOTE,
    ACTIONS(20), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(25), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(28), 1,
      sym_lparen,
    ACTIONS(31), 1,
      sym_lbrace,
    ACTIONS(34), 1,
      sym_lbracket,
    ACTIONS(23), 3,
      anon_sym_RBRACE,
      sym_rparen,
      sym_rbracket,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [64] = 9,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    STATE(68), 1,
      sym_rbrace,
    STATE(6), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [96] = 9,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_rbrace,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [128] = 9,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    STATE(78), 1,
      sym_rbrace,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [160] = 9,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym_rbrace,
    STATE(5), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [192] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(53), 1,
      sym_rbracket,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [221] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(79), 2,
      sym__e,
      sym_string,
    STATE(116), 2,
      sym__expr3,
      sym_apply3,
    STATE(82), 4,
      sym__expr2,
      sym__expr1,
      sym_apply2,
      sym_apply1,
  [248] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(13), 1,
      sym_id,
    STATE(87), 2,
      sym__e,
      sym_string,
    STATE(108), 2,
      sym__expr3,
      sym_apply3,
    STATE(90), 4,
      sym__expr2,
      sym__expr1,
      sym_apply2,
      sym_apply1,
  [275] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(53), 1,
      sym_rparen,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [304] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(55), 1,
      sym_rbracket,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [333] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(55), 1,
      sym_rparen,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [362] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(57), 1,
      sym_rparen,
    STATE(13), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [391] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(13), 1,
      sym_id,
    STATE(87), 2,
      sym__e,
      sym_string,
    STATE(111), 2,
      sym__expr3,
      sym_apply3,
    STATE(90), 4,
      sym__expr2,
      sym__expr1,
      sym_apply2,
      sym_apply1,
  [418] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(13), 1,
      sym_id,
    STATE(87), 2,
      sym__e,
      sym_string,
    STATE(118), 2,
      sym__expr3,
      sym_apply3,
    STATE(90), 4,
      sym__expr2,
      sym__expr1,
      sym_apply2,
      sym_apply1,
  [445] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(57), 1,
      sym_rbracket,
    STATE(12), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [474] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(79), 2,
      sym__e,
      sym_string,
    STATE(117), 2,
      sym__expr3,
      sym_apply3,
    STATE(82), 4,
      sym__expr2,
      sym__expr1,
      sym_apply2,
      sym_apply1,
  [501] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(59), 1,
      sym_rparen,
    STATE(11), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [530] = 8,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(43), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(45), 1,
      sym_lparen,
    ACTIONS(47), 1,
      sym_lbrace,
    ACTIONS(49), 1,
      sym_lbracket,
    ACTIONS(59), 1,
      sym_rbracket,
    STATE(8), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [559] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(13), 1,
      sym_id,
    STATE(87), 2,
      sym__e,
      sym_string,
    STATE(96), 2,
      sym__expr3,
      sym_apply3,
    STATE(90), 4,
      sym__expr2,
      sym__expr1,
      sym_apply2,
      sym_apply1,
  [586] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(61), 1,
      anon_sym_BQUOTE2,
    ACTIONS(63), 1,
      sym_id,
    ACTIONS(65), 1,
      sym__linefeed,
    STATE(95), 2,
      sym__e,
      sym_string,
    STATE(109), 3,
      sym__expri,
      sym_applyi,
      sym__codeblock,
  [611] = 6,
    ACTIONS(67), 1,
      anon_sym_BQUOTE,
    ACTIONS(69), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(73), 1,
      aux_sym_stx_word_token1,
    ACTIONS(75), 1,
      sym__space,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      sym__linefeed,
    STATE(27), 4,
      sym_interpol8,
      sym_stx_word,
      sym__linesplit,
      aux_sym__stx_words_repeat1,
  [634] = 6,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(83), 1,
      sym__linefeed,
    STATE(89), 1,
      sym_linefeed,
    ACTIONS(79), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_dquo_token1,
    STATE(45), 4,
      sym_interpol8,
      sym_stx_dquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [657] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(61), 1,
      anon_sym_BQUOTE2,
    ACTIONS(63), 1,
      sym_id,
    ACTIONS(85), 1,
      sym__linefeed,
    STATE(95), 2,
      sym__e,
      sym_string,
    STATE(113), 3,
      sym__expri,
      sym_applyi,
      sym__codeblock,
  [682] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(61), 1,
      anon_sym_BQUOTE2,
    ACTIONS(63), 1,
      sym_id,
    ACTIONS(87), 1,
      sym__linefeed,
    STATE(95), 2,
      sym__e,
      sym_string,
    STATE(97), 3,
      sym__expri,
      sym_applyi,
      sym__codeblock,
  [707] = 6,
    ACTIONS(89), 1,
      anon_sym_BQUOTE,
    ACTIONS(92), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(97), 1,
      aux_sym_stx_word_token1,
    ACTIONS(100), 1,
      sym__space,
    ACTIONS(95), 2,
      anon_sym_RBRACE,
      sym__linefeed,
    STATE(27), 4,
      sym_interpol8,
      sym_stx_word,
      sym__linesplit,
      aux_sym__stx_words_repeat1,
  [730] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(61), 1,
      anon_sym_BQUOTE2,
    ACTIONS(63), 1,
      sym_id,
    ACTIONS(102), 1,
      sym__linefeed,
    STATE(95), 2,
      sym__e,
      sym_string,
    STATE(98), 3,
      sym__expri,
      sym_applyi,
      sym__codeblock,
  [755] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(61), 1,
      anon_sym_BQUOTE2,
    ACTIONS(63), 1,
      sym_id,
    ACTIONS(104), 1,
      sym__linefeed,
    STATE(95), 2,
      sym__e,
      sym_string,
    STATE(103), 3,
      sym__expri,
      sym_applyi,
      sym__codeblock,
  [780] = 2,
    ACTIONS(106), 1,
      anon_sym_BQUOTE,
    ACTIONS(108), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [794] = 5,
    ACTIONS(113), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(116), 1,
      sym__space,
    ACTIONS(118), 1,
      sym__linefeed,
    ACTIONS(110), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(31), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [814] = 4,
    ACTIONS(122), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(120), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      sym__space,
    STATE(41), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [832] = 2,
    ACTIONS(126), 1,
      anon_sym_BQUOTE,
    ACTIONS(128), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [846] = 2,
    ACTIONS(130), 1,
      anon_sym_BQUOTE,
    ACTIONS(132), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [860] = 2,
    ACTIONS(134), 1,
      anon_sym_BQUOTE,
    ACTIONS(136), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [874] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(13), 1,
      sym_id,
    STATE(85), 1,
      sym_apply2,
    STATE(84), 2,
      sym__expr1,
      sym_apply1,
    STATE(87), 2,
      sym__e,
      sym_string,
  [898] = 2,
    ACTIONS(138), 1,
      anon_sym_BQUOTE,
    ACTIONS(140), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [912] = 2,
    ACTIONS(142), 1,
      anon_sym_BQUOTE,
    ACTIONS(144), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [926] = 5,
    ACTIONS(148), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(150), 1,
      sym__linefeed,
    STATE(70), 1,
      sym_linefeed,
    ACTIONS(146), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(31), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [946] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(80), 1,
      sym_apply2,
    STATE(79), 2,
      sym__e,
      sym_string,
    STATE(81), 2,
      sym__expr1,
      sym_apply1,
  [970] = 4,
    ACTIONS(155), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(116), 2,
      anon_sym_RBRACE,
      sym__space,
    ACTIONS(152), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(41), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [988] = 5,
    ACTIONS(124), 1,
      sym__space,
    ACTIONS(148), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(158), 1,
      sym__linefeed,
    ACTIONS(146), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(31), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [1008] = 5,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      anon_sym_BQUOTE,
    ACTIONS(165), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(168), 1,
      aux_sym_stx_dquo_token1,
    STATE(43), 4,
      sym_interpol8,
      sym_stx_dquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [1027] = 6,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(61), 1,
      anon_sym_BQUOTE2,
    ACTIONS(63), 1,
      sym_id,
    STATE(95), 2,
      sym__e,
      sym_string,
    STATE(107), 2,
      sym__expri,
      sym_applyi,
  [1048] = 5,
    ACTIONS(79), 1,
      anon_sym_BQUOTE,
    ACTIONS(81), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(171), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      aux_sym_stx_dquo_token1,
    STATE(43), 4,
      sym_interpol8,
      sym_stx_dquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [1067] = 6,
    ACTIONS(175), 1,
      sym_lparen,
    ACTIONS(177), 1,
      sym_lbrace,
    ACTIONS(179), 1,
      sym_lbracket,
    STATE(47), 1,
      sym_stx_word,
    ACTIONS(73), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_word_token1,
    STATE(76), 2,
      sym__stx_words,
      sym__stx_group,
  [1088] = 4,
    ACTIONS(67), 1,
      anon_sym_BQUOTE,
    ACTIONS(69), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(73), 1,
      aux_sym_stx_word_token1,
    STATE(23), 4,
      sym_interpol8,
      sym_stx_word,
      sym__linesplit,
      aux_sym__stx_words_repeat1,
  [1104] = 4,
    ACTIONS(120), 1,
      anon_sym_BQUOTE,
    ACTIONS(122), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(181), 1,
      aux_sym_stx_line_token1,
    STATE(32), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [1120] = 4,
    ACTIONS(146), 1,
      anon_sym_BQUOTE,
    ACTIONS(148), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(183), 1,
      aux_sym_stx_line_token1,
    STATE(42), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [1136] = 4,
    ACTIONS(146), 1,
      anon_sym_BQUOTE,
    ACTIONS(148), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(183), 1,
      aux_sym_stx_line_token1,
    STATE(39), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [1152] = 2,
    ACTIONS(134), 2,
      anon_sym_BQUOTE,
      sym__space,
    ACTIONS(136), 4,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_word_token1,
      sym__linefeed,
  [1163] = 2,
    ACTIONS(138), 2,
      anon_sym_BQUOTE,
      sym__space,
    ACTIONS(140), 4,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_word_token1,
      sym__linefeed,
  [1174] = 2,
    ACTIONS(185), 2,
      anon_sym_BQUOTE,
      sym__space,
    ACTIONS(187), 4,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_word_token1,
      sym__linefeed,
  [1185] = 2,
    ACTIONS(140), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(138), 4,
      anon_sym_BQUOTE,
      anon_sym_RBRACE,
      aux_sym_stx_line_token1,
      sym__space,
  [1195] = 2,
    ACTIONS(140), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(138), 3,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
      sym__space,
  [1205] = 4,
    ACTIONS(189), 1,
      sym__indent,
    ACTIONS(191), 1,
      sym__dedent,
    ACTIONS(193), 1,
      sym__break,
    STATE(59), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1219] = 4,
    ACTIONS(189), 1,
      sym__indent,
    ACTIONS(193), 1,
      sym__break,
    ACTIONS(195), 1,
      sym__dedent,
    STATE(59), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1233] = 2,
    ACTIONS(199), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(197), 3,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
      sym__space,
  [1243] = 4,
    ACTIONS(201), 1,
      sym__indent,
    ACTIONS(204), 1,
      sym__dedent,
    ACTIONS(206), 1,
      sym__break,
    STATE(59), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1257] = 2,
    ACTIONS(136), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(134), 4,
      anon_sym_BQUOTE,
      anon_sym_RBRACE,
      aux_sym_stx_line_token1,
      sym__space,
  [1267] = 2,
    ACTIONS(136), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(134), 3,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
      sym__space,
  [1277] = 2,
    ACTIONS(199), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(197), 4,
      anon_sym_BQUOTE,
      anon_sym_RBRACE,
      aux_sym_stx_line_token1,
      sym__space,
  [1287] = 2,
    ACTIONS(138), 1,
      anon_sym_BQUOTE,
    ACTIONS(140), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_stx_dquo_token1,
  [1296] = 3,
    ACTIONS(189), 1,
      sym__indent,
    ACTIONS(193), 1,
      sym__break,
    STATE(57), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1307] = 2,
    ACTIONS(134), 1,
      anon_sym_BQUOTE,
    ACTIONS(136), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_stx_dquo_token1,
  [1316] = 2,
    ACTIONS(211), 1,
      anon_sym_BQUOTE,
    ACTIONS(209), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_stx_dquo_token1,
  [1325] = 3,
    ACTIONS(189), 1,
      sym__indent,
    ACTIONS(193), 1,
      sym__break,
    STATE(56), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1336] = 2,
    ACTIONS(126), 1,
      sym__space,
    ACTIONS(128), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1344] = 1,
    ACTIONS(213), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [1350] = 1,
    ACTIONS(215), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [1356] = 2,
    ACTIONS(219), 1,
      sym__indent,
    ACTIONS(217), 2,
      sym__break,
      ts_builtin_sym_end,
  [1364] = 2,
    ACTIONS(223), 1,
      sym__space,
    ACTIONS(221), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1372] = 2,
    ACTIONS(227), 1,
      sym__space,
    ACTIONS(225), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1380] = 2,
    ACTIONS(142), 1,
      sym__space,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1388] = 1,
    ACTIONS(229), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [1394] = 2,
    ACTIONS(124), 1,
      sym__space,
    ACTIONS(158), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1402] = 2,
    ACTIONS(231), 1,
      sym__indent,
    ACTIONS(217), 2,
      sym__dedent,
      sym__break,
  [1410] = 2,
    ACTIONS(106), 1,
      sym__space,
    ACTIONS(108), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1418] = 2,
    ACTIONS(233), 1,
      sym__space,
    ACTIONS(235), 1,
      sym__linefeed,
  [1425] = 1,
    ACTIONS(237), 2,
      sym__break,
      ts_builtin_sym_end,
  [1430] = 1,
    ACTIONS(239), 2,
      sym__break,
      ts_builtin_sym_end,
  [1435] = 2,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
    ACTIONS(243), 1,
      sym__break,
  [1442] = 2,
    ACTIONS(245), 1,
      sym__indent,
    ACTIONS(247), 1,
      sym__break,
  [1449] = 1,
    ACTIONS(239), 2,
      sym__dedent,
      sym__break,
  [1454] = 1,
    ACTIONS(237), 2,
      sym__dedent,
      sym__break,
  [1459] = 2,
    ACTIONS(245), 1,
      sym__indent,
    ACTIONS(249), 1,
      sym__break,
  [1466] = 2,
    ACTIONS(251), 1,
      sym__space,
    ACTIONS(253), 1,
      sym__linefeed,
  [1473] = 1,
    ACTIONS(255), 2,
      sym__dedent,
      sym__break,
  [1478] = 2,
    ACTIONS(257), 1,
      sym__indent,
    STATE(101), 1,
      sym_blockquoted,
  [1485] = 2,
    ACTIONS(241), 1,
      sym__dedent,
    ACTIONS(259), 1,
      sym__break,
  [1492] = 2,
    ACTIONS(245), 1,
      sym__indent,
    ACTIONS(261), 1,
      sym__break,
  [1499] = 2,
    ACTIONS(245), 1,
      sym__indent,
    ACTIONS(263), 1,
      sym__break,
  [1506] = 1,
    ACTIONS(255), 2,
      sym__break,
      ts_builtin_sym_end,
  [1511] = 2,
    ACTIONS(245), 1,
      sym__indent,
    ACTIONS(265), 1,
      sym__break,
  [1518] = 2,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    ACTIONS(269), 1,
      sym__space,
  [1525] = 1,
    ACTIONS(271), 1,
      sym__dedent,
  [1529] = 1,
    ACTIONS(273), 1,
      anon_sym_RBRACE,
  [1533] = 1,
    ACTIONS(275), 1,
      anon_sym_RBRACE,
  [1537] = 1,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
  [1541] = 1,
    ACTIONS(279), 1,
      anon_sym_DQUOTE,
  [1545] = 1,
    ACTIONS(281), 1,
      sym__break,
  [1549] = 1,
    ACTIONS(283), 1,
      anon_sym_RBRACE,
  [1553] = 1,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
  [1557] = 1,
    ACTIONS(229), 1,
      sym__indent,
  [1561] = 1,
    ACTIONS(213), 1,
      sym__break,
  [1565] = 1,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
  [1569] = 1,
    ACTIONS(289), 1,
      anon_sym_RBRACE,
  [1573] = 1,
    ACTIONS(291), 1,
      sym__dedent,
  [1577] = 1,
    ACTIONS(293), 1,
      anon_sym_RBRACE,
  [1581] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
  [1585] = 1,
    ACTIONS(297), 1,
      sym__dedent,
  [1589] = 1,
    ACTIONS(299), 1,
      anon_sym_RBRACE,
  [1593] = 1,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
  [1597] = 1,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
  [1601] = 1,
    ACTIONS(305), 1,
      sym__break,
  [1605] = 1,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
  [1609] = 1,
    ACTIONS(307), 1,
      ts_builtin_sym_end,
  [1613] = 1,
    ACTIONS(307), 1,
      sym__dedent,
  [1617] = 1,
    ACTIONS(309), 1,
      sym__dedent,
  [1621] = 1,
    ACTIONS(311), 1,
      sym__break,
  [1625] = 1,
    ACTIONS(313), 1,
      sym__break,
  [1629] = 1,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
  [1633] = 1,
    ACTIONS(317), 1,
      sym__break,
  [1637] = 1,
    ACTIONS(319), 1,
      ts_builtin_sym_end,
  [1641] = 1,
    ACTIONS(315), 1,
      sym__dedent,
  [1645] = 1,
    ACTIONS(321), 1,
      sym__break,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 221,
  [SMALL_STATE(10)] = 248,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 304,
  [SMALL_STATE(13)] = 333,
  [SMALL_STATE(14)] = 362,
  [SMALL_STATE(15)] = 391,
  [SMALL_STATE(16)] = 418,
  [SMALL_STATE(17)] = 445,
  [SMALL_STATE(18)] = 474,
  [SMALL_STATE(19)] = 501,
  [SMALL_STATE(20)] = 530,
  [SMALL_STATE(21)] = 559,
  [SMALL_STATE(22)] = 586,
  [SMALL_STATE(23)] = 611,
  [SMALL_STATE(24)] = 634,
  [SMALL_STATE(25)] = 657,
  [SMALL_STATE(26)] = 682,
  [SMALL_STATE(27)] = 707,
  [SMALL_STATE(28)] = 730,
  [SMALL_STATE(29)] = 755,
  [SMALL_STATE(30)] = 780,
  [SMALL_STATE(31)] = 794,
  [SMALL_STATE(32)] = 814,
  [SMALL_STATE(33)] = 832,
  [SMALL_STATE(34)] = 846,
  [SMALL_STATE(35)] = 860,
  [SMALL_STATE(36)] = 874,
  [SMALL_STATE(37)] = 898,
  [SMALL_STATE(38)] = 912,
  [SMALL_STATE(39)] = 926,
  [SMALL_STATE(40)] = 946,
  [SMALL_STATE(41)] = 970,
  [SMALL_STATE(42)] = 988,
  [SMALL_STATE(43)] = 1008,
  [SMALL_STATE(44)] = 1027,
  [SMALL_STATE(45)] = 1048,
  [SMALL_STATE(46)] = 1067,
  [SMALL_STATE(47)] = 1088,
  [SMALL_STATE(48)] = 1104,
  [SMALL_STATE(49)] = 1120,
  [SMALL_STATE(50)] = 1136,
  [SMALL_STATE(51)] = 1152,
  [SMALL_STATE(52)] = 1163,
  [SMALL_STATE(53)] = 1174,
  [SMALL_STATE(54)] = 1185,
  [SMALL_STATE(55)] = 1195,
  [SMALL_STATE(56)] = 1205,
  [SMALL_STATE(57)] = 1219,
  [SMALL_STATE(58)] = 1233,
  [SMALL_STATE(59)] = 1243,
  [SMALL_STATE(60)] = 1257,
  [SMALL_STATE(61)] = 1267,
  [SMALL_STATE(62)] = 1277,
  [SMALL_STATE(63)] = 1287,
  [SMALL_STATE(64)] = 1296,
  [SMALL_STATE(65)] = 1307,
  [SMALL_STATE(66)] = 1316,
  [SMALL_STATE(67)] = 1325,
  [SMALL_STATE(68)] = 1336,
  [SMALL_STATE(69)] = 1344,
  [SMALL_STATE(70)] = 1350,
  [SMALL_STATE(71)] = 1356,
  [SMALL_STATE(72)] = 1364,
  [SMALL_STATE(73)] = 1372,
  [SMALL_STATE(74)] = 1380,
  [SMALL_STATE(75)] = 1388,
  [SMALL_STATE(76)] = 1394,
  [SMALL_STATE(77)] = 1402,
  [SMALL_STATE(78)] = 1410,
  [SMALL_STATE(79)] = 1418,
  [SMALL_STATE(80)] = 1425,
  [SMALL_STATE(81)] = 1430,
  [SMALL_STATE(82)] = 1435,
  [SMALL_STATE(83)] = 1442,
  [SMALL_STATE(84)] = 1449,
  [SMALL_STATE(85)] = 1454,
  [SMALL_STATE(86)] = 1459,
  [SMALL_STATE(87)] = 1466,
  [SMALL_STATE(88)] = 1473,
  [SMALL_STATE(89)] = 1478,
  [SMALL_STATE(90)] = 1485,
  [SMALL_STATE(91)] = 1492,
  [SMALL_STATE(92)] = 1499,
  [SMALL_STATE(93)] = 1506,
  [SMALL_STATE(94)] = 1511,
  [SMALL_STATE(95)] = 1518,
  [SMALL_STATE(96)] = 1525,
  [SMALL_STATE(97)] = 1529,
  [SMALL_STATE(98)] = 1533,
  [SMALL_STATE(99)] = 1537,
  [SMALL_STATE(100)] = 1541,
  [SMALL_STATE(101)] = 1545,
  [SMALL_STATE(102)] = 1549,
  [SMALL_STATE(103)] = 1553,
  [SMALL_STATE(104)] = 1557,
  [SMALL_STATE(105)] = 1561,
  [SMALL_STATE(106)] = 1565,
  [SMALL_STATE(107)] = 1569,
  [SMALL_STATE(108)] = 1573,
  [SMALL_STATE(109)] = 1577,
  [SMALL_STATE(110)] = 1581,
  [SMALL_STATE(111)] = 1585,
  [SMALL_STATE(112)] = 1589,
  [SMALL_STATE(113)] = 1593,
  [SMALL_STATE(114)] = 1597,
  [SMALL_STATE(115)] = 1601,
  [SMALL_STATE(116)] = 1605,
  [SMALL_STATE(117)] = 1609,
  [SMALL_STATE(118)] = 1613,
  [SMALL_STATE(119)] = 1617,
  [SMALL_STATE(120)] = 1621,
  [SMALL_STATE(121)] = 1625,
  [SMALL_STATE(122)] = 1629,
  [SMALL_STATE(123)] = 1633,
  [SMALL_STATE(124)] = 1637,
  [SMALL_STATE(125)] = 1641,
  [SMALL_STATE(126)] = 1645,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(.symbol = aux_sym__stx_group_repeat1, .child_count = 2), SHIFT_REPEAT(34),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_group_repeat1, .child_count = 2), SHIFT_REPEAT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_group_repeat1, .child_count = 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_group_repeat1, .child_count = 2), SHIFT_REPEAT(34),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_group_repeat1, .child_count = 2), SHIFT_REPEAT(14),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_group_repeat1, .child_count = 2), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_group_repeat1, .child_count = 2), SHIFT_REPEAT(17),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__stx_words, .child_count = 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym__stx_words, .child_count = 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(.symbol = aux_sym__stx_words_repeat1, .child_count = 2), SHIFT_REPEAT(53),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_words_repeat1, .child_count = 2), SHIFT_REPEAT(26),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_words_repeat1, .child_count = 2),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym__stx_words_repeat1, .child_count = 2), SHIFT_REPEAT(53),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = aux_sym__stx_words_repeat1, .child_count = 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym__stx_group, .child_count = 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__stx_group, .child_count = 3),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(.symbol = aux_sym_string_repeat2, .child_count = 2), SHIFT_REPEAT(58),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym_string_repeat2, .child_count = 2), SHIFT_REPEAT(29),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = aux_sym_string_repeat2, .child_count = 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = aux_sym_string_repeat2, .child_count = 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_string, .child_count = 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym__stx_group, .child_count = 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__stx_group, .child_count = 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_stx_bloc, .child_count = 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_stx_bloc, .child_count = 1),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym__linesplit, .child_count = 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__linesplit, .child_count = 4),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_interpol8, .child_count = 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_interpol8, .child_count = 3),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_rbrace, .child_count = 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_rbrace, .child_count = 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(.symbol = aux_sym_string_repeat2, .child_count = 2), SHIFT_REPEAT(62),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym_string_repeat2, .child_count = 2), SHIFT_REPEAT(25),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_string, .child_count = 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = aux_sym_string_repeat1, .child_count = 2),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(.symbol = aux_sym_string_repeat1, .child_count = 2), SHIFT_REPEAT(66),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym_string_repeat1, .child_count = 2), SHIFT_REPEAT(28),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym_string_repeat1, .child_count = 2), SHIFT_REPEAT(66),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_stx_word, .child_count = 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_stx_word, .child_count = 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_stx_line, .child_count = 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_stx_line, .child_count = 1),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym_blockquoted_repeat1, .child_count = 2), SHIFT_REPEAT(64),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = aux_sym_blockquoted_repeat1, .child_count = 2),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(.symbol = aux_sym_blockquoted_repeat1, .child_count = 2), SHIFT_REPEAT(50),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_stx_dquo, .child_count = 1),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_stx_dquo, .child_count = 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_blockquoted, .child_count = 3),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = aux_sym_blockquoted_repeat1, .child_count = 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__expr1, .child_count = 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_string, .child_count = 3),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_string, .child_count = 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_string, .child_count = 5),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(.symbol = sym_string, .child_count = 5),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_linefeed, .child_count = 1),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_apply2, .child_count = 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_apply1, .child_count = 3),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__expr3, .child_count = 1),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_apply2, .child_count = 6),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__expri, .child_count = 1),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_program, .child_count = 3),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym__codeblock, .child_count = 5),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_applyi, .child_count = 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_apply3, .child_count = 3),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(.symbol = sym_program, .child_count = 1),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [319] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__break = 2,
  ts_external_token__sentinel = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__break] = sym__break,
  [ts_external_token__sentinel] = sym__sentinel,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
    [ts_external_token__sentinel] = true,
  },
  [2] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
    [ts_external_token__break] = true,
  },
  [4] = {
    [ts_external_token__break] = true,
  },
  [5] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
  [7] = {
    [ts_external_token__dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_bilang_external_scanner_create(void);
void tree_sitter_bilang_external_scanner_destroy(void *);
bool tree_sitter_bilang_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_bilang_external_scanner_serialize(void *, char *);
void tree_sitter_bilang_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bilang() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_bilang_external_scanner_create,
      tree_sitter_bilang_external_scanner_destroy,
      tree_sitter_bilang_external_scanner_scan,
      tree_sitter_bilang_external_scanner_serialize,
      tree_sitter_bilang_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
