#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_DQUOTE = 1,
  anon_sym_BQUOTE_LBRACE = 2,
  anon_sym_RBRACE = 3,
  aux_sym_texline_token1 = 4,
  anon_sym_BQUOTE = 5,
  aux_sym_texdquo_token1 = 6,
  sym_id = 7,
  sym__space = 8,
  sym__linefeed = 9,
  sym__indent = 10,
  sym__dedent = 11,
  sym__break = 12,
  sym__sentinel = 13,
  sym_program = 14,
  sym__expr3 = 15,
  sym__expr2 = 16,
  sym__expr1 = 17,
  sym__exprL = 18,
  sym_apply3 = 19,
  sym_apply2 = 20,
  sym_apply1 = 21,
  sym__e = 22,
  sym_string = 23,
  sym_blockquoted = 24,
  sym_interpol8 = 25,
  sym_texline = 26,
  sym_texdquo = 27,
  sym_linefeed = 28,
  sym__linesplit = 29,
  aux_sym_string_repeat1 = 30,
  aux_sym_blockquoted_repeat1 = 31,
  aux_sym_blockquoted_repeat2 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BQUOTE_LBRACE] = "`{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_texline_token1] = "texline_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_texdquo_token1] = "texdquo_token1",
  [sym_id] = "id",
  [sym__space] = "_space",
  [sym__linefeed] = "_linefeed",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__break] = "_break",
  [sym__sentinel] = "_sentinel",
  [sym_program] = "program",
  [sym__expr3] = "_expr3",
  [sym__expr2] = "_expr2",
  [sym__expr1] = "_expr1",
  [sym__exprL] = "_exprL",
  [sym_apply3] = "apply3",
  [sym_apply2] = "apply2",
  [sym_apply1] = "apply1",
  [sym__e] = "_e",
  [sym_string] = "string",
  [sym_blockquoted] = "blockquoted",
  [sym_interpol8] = "interpol8",
  [sym_texline] = "texline",
  [sym_texdquo] = "texdquo",
  [sym_linefeed] = "linefeed",
  [sym__linesplit] = "_linesplit",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_blockquoted_repeat1] = "blockquoted_repeat1",
  [aux_sym_blockquoted_repeat2] = "blockquoted_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BQUOTE_LBRACE] = anon_sym_BQUOTE_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_texline_token1] = aux_sym_texline_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_texdquo_token1] = aux_sym_texdquo_token1,
  [sym_id] = sym_id,
  [sym__space] = sym__space,
  [sym__linefeed] = sym__linefeed,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__break] = sym__break,
  [sym__sentinel] = sym__sentinel,
  [sym_program] = sym_program,
  [sym__expr3] = sym__expr3,
  [sym__expr2] = sym__expr2,
  [sym__expr1] = sym__expr1,
  [sym__exprL] = sym__exprL,
  [sym_apply3] = sym_apply3,
  [sym_apply2] = sym_apply2,
  [sym_apply1] = sym_apply1,
  [sym__e] = sym__e,
  [sym_string] = sym_string,
  [sym_blockquoted] = sym_blockquoted,
  [sym_interpol8] = sym_interpol8,
  [sym_texline] = sym_texline,
  [sym_texdquo] = sym_texdquo,
  [sym_linefeed] = sym_linefeed,
  [sym__linesplit] = sym__linesplit,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_blockquoted_repeat1] = aux_sym_blockquoted_repeat1,
  [aux_sym_blockquoted_repeat2] = aux_sym_blockquoted_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_texline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_texdquo_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__linefeed] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__break] = {
    .visible = false,
    .named = true,
  },
  [sym__sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__expr3] = {
    .visible = false,
    .named = true,
  },
  [sym__expr2] = {
    .visible = false,
    .named = true,
  },
  [sym__expr1] = {
    .visible = false,
    .named = true,
  },
  [sym__exprL] = {
    .visible = false,
    .named = true,
  },
  [sym_apply3] = {
    .visible = true,
    .named = true,
  },
  [sym_apply2] = {
    .visible = true,
    .named = true,
  },
  [sym_apply1] = {
    .visible = true,
    .named = true,
  },
  [sym__e] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_blockquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_interpol8] = {
    .visible = true,
    .named = true,
  },
  [sym_texline] = {
    .visible = true,
    .named = true,
  },
  [sym_texdquo] = {
    .visible = true,
    .named = true,
  },
  [sym_linefeed] = {
    .visible = true,
    .named = true,
  },
  [sym__linesplit] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blockquoted_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blockquoted_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 24,
  [29] = 25,
  [30] = 23,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 33,
  [38] = 38,
  [39] = 39,
  [40] = 34,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 43,
  [46] = 44,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 47,
  [51] = 39,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 32,
  [62] = 62,
  [63] = 52,
  [64] = 64,
  [65] = 57,
  [66] = 66,
  [67] = 55,
  [68] = 56,
  [69] = 53,
  [70] = 64,
  [71] = 71,
  [72] = 72,
  [73] = 72,
  [74] = 71,
  [75] = 66,
  [76] = 60,
  [77] = 58,
  [78] = 78,
  [79] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_BQUOTE_LBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_texline_token1);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_texline_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '{') ADVANCE(8);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_texdquo_token1);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '`') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_texdquo_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '`') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_id);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__linefeed);
      if (lookahead == '\t') ADVANCE(17);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0, .external_lex_state = 4},
  [44] = {.lex_state = 0, .external_lex_state = 4},
  [45] = {.lex_state = 0, .external_lex_state = 5},
  [46] = {.lex_state = 0, .external_lex_state = 5},
  [47] = {.lex_state = 0, .external_lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0, .external_lex_state = 6},
  [50] = {.lex_state = 0, .external_lex_state = 3},
  [51] = {.lex_state = 0, .external_lex_state = 6},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0, .external_lex_state = 7},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0, .external_lex_state = 7},
  [57] = {.lex_state = 0, .external_lex_state = 7},
  [58] = {.lex_state = 0, .external_lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 0, .external_lex_state = 7},
  [61] = {.lex_state = 0, .external_lex_state = 5},
  [62] = {.lex_state = 0, .external_lex_state = 5},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0, .external_lex_state = 7},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0, .external_lex_state = 7},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0, .external_lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0, .external_lex_state = 5},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0, .external_lex_state = 7},
  [77] = {.lex_state = 0, .external_lex_state = 5},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0, .external_lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [sym__linefeed] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__break] = ACTIONS(1),
    [sym__sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(78),
    [sym__expr3] = STATE(75),
    [sym__expr2] = STATE(46),
    [sym__expr1] = STATE(72),
    [sym__exprL] = STATE(34),
    [sym_apply3] = STATE(75),
    [sym_apply2] = STATE(46),
    [sym_apply1] = STATE(72),
    [sym__e] = STATE(35),
    [sym_string] = STATE(35),
    [anon_sym_DQUOTE] = ACTIONS(3),
    [sym_id] = ACTIONS(5),
    [sym__linefeed] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    ACTIONS(9), 1,
      sym__linefeed,
    STATE(40), 1,
      sym__exprL,
    STATE(60), 1,
      sym_program,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(44), 2,
      sym__expr2,
      sym_apply2,
    STATE(66), 2,
      sym__expr3,
      sym_apply3,
    STATE(73), 2,
      sym__expr1,
      sym_apply1,
  [32] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    ACTIONS(9), 1,
      sym__linefeed,
    STATE(40), 1,
      sym__exprL,
    STATE(76), 1,
      sym_program,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(44), 2,
      sym__expr2,
      sym_apply2,
    STATE(66), 2,
      sym__expr3,
      sym_apply3,
    STATE(73), 2,
      sym__expr1,
      sym_apply1,
  [64] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    STATE(34), 1,
      sym__exprL,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(46), 2,
      sym__expr2,
      sym_apply2,
    STATE(68), 2,
      sym__expr3,
      sym_apply3,
    STATE(72), 2,
      sym__expr1,
      sym_apply1,
  [90] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    STATE(40), 1,
      sym__exprL,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(44), 2,
      sym__expr2,
      sym_apply2,
    STATE(53), 2,
      sym__expr3,
      sym_apply3,
    STATE(73), 2,
      sym__expr1,
      sym_apply1,
  [116] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    STATE(40), 1,
      sym__exprL,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(44), 2,
      sym__expr2,
      sym_apply2,
    STATE(57), 2,
      sym__expr3,
      sym_apply3,
    STATE(73), 2,
      sym__expr1,
      sym_apply1,
  [142] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    STATE(40), 1,
      sym__exprL,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(44), 2,
      sym__expr2,
      sym_apply2,
    STATE(56), 2,
      sym__expr3,
      sym_apply3,
    STATE(73), 2,
      sym__expr1,
      sym_apply1,
  [168] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    STATE(40), 1,
      sym__exprL,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(44), 2,
      sym__expr2,
      sym_apply2,
    STATE(69), 2,
      sym__expr3,
      sym_apply3,
    STATE(73), 2,
      sym__expr1,
      sym_apply1,
  [194] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    STATE(34), 1,
      sym__exprL,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(46), 2,
      sym__expr2,
      sym_apply2,
    STATE(65), 2,
      sym__expr3,
      sym_apply3,
    STATE(72), 2,
      sym__expr1,
      sym_apply1,
  [220] = 6,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(17), 1,
      sym__linefeed,
    STATE(49), 1,
      sym_linefeed,
    ACTIONS(15), 2,
      anon_sym_BQUOTE,
      aux_sym_texdquo_token1,
    STATE(12), 4,
      sym_interpol8,
      sym_texdquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [243] = 5,
    ACTIONS(19), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(23), 1,
      sym__linefeed,
    STATE(41), 1,
      sym_linefeed,
    ACTIONS(21), 2,
      aux_sym_texline_token1,
      anon_sym_BQUOTE,
    STATE(14), 4,
      sym_interpol8,
      sym_texline,
      sym__linesplit,
      aux_sym_blockquoted_repeat1,
  [263] = 5,
    ACTIONS(13), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(15), 1,
      anon_sym_BQUOTE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_texdquo_token1,
    STATE(13), 4,
      sym_interpol8,
      sym_texdquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [282] = 5,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(34), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      aux_sym_texdquo_token1,
    STATE(13), 4,
      sym_interpol8,
      sym_texdquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [301] = 4,
    ACTIONS(40), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(46), 1,
      sym__linefeed,
    ACTIONS(43), 2,
      aux_sym_texline_token1,
      anon_sym_BQUOTE,
    STATE(14), 4,
      sym_interpol8,
      sym_texline,
      sym__linesplit,
      aux_sym_blockquoted_repeat1,
  [318] = 5,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    ACTIONS(48), 1,
      sym__linefeed,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(63), 2,
      sym__expr1,
      sym_apply1,
  [336] = 5,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    ACTIONS(50), 1,
      sym__linefeed,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(52), 2,
      sym__expr1,
      sym_apply1,
  [354] = 4,
    ACTIONS(19), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(21), 1,
      anon_sym_BQUOTE,
    ACTIONS(52), 1,
      aux_sym_texline_token1,
    STATE(11), 4,
      sym_interpol8,
      sym_texline,
      sym__linesplit,
      aux_sym_blockquoted_repeat1,
  [370] = 4,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      sym_id,
    STATE(35), 2,
      sym__e,
      sym_string,
    STATE(48), 2,
      sym__expr1,
      sym_apply1,
  [385] = 4,
    ACTIONS(54), 1,
      sym__indent,
    ACTIONS(57), 1,
      sym__dedent,
    ACTIONS(59), 1,
      sym__break,
    STATE(19), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat2,
  [399] = 4,
    ACTIONS(62), 1,
      sym__indent,
    ACTIONS(64), 1,
      sym__dedent,
    ACTIONS(66), 1,
      sym__break,
    STATE(19), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat2,
  [413] = 4,
    ACTIONS(62), 1,
      sym__indent,
    ACTIONS(66), 1,
      sym__break,
    ACTIONS(68), 1,
      sym__dedent,
    STATE(19), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat2,
  [427] = 2,
    ACTIONS(72), 1,
      anon_sym_BQUOTE,
    ACTIONS(70), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_texdquo_token1,
  [436] = 2,
    ACTIONS(74), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(76), 2,
      aux_sym_texline_token1,
      anon_sym_BQUOTE,
  [445] = 2,
    ACTIONS(78), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(80), 2,
      aux_sym_texline_token1,
      anon_sym_BQUOTE,
  [454] = 2,
    ACTIONS(84), 1,
      anon_sym_BQUOTE,
    ACTIONS(82), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_texdquo_token1,
  [463] = 3,
    ACTIONS(62), 1,
      sym__indent,
    ACTIONS(66), 1,
      sym__break,
    STATE(20), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat2,
  [474] = 3,
    ACTIONS(62), 1,
      sym__indent,
    ACTIONS(66), 1,
      sym__break,
    STATE(21), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat2,
  [485] = 2,
    ACTIONS(80), 1,
      anon_sym_BQUOTE,
    ACTIONS(78), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_texdquo_token1,
  [494] = 2,
    ACTIONS(82), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(84), 2,
      aux_sym_texline_token1,
      anon_sym_BQUOTE,
  [503] = 2,
    ACTIONS(76), 1,
      anon_sym_BQUOTE,
    ACTIONS(74), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_texdquo_token1,
  [512] = 2,
    ACTIONS(86), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(88), 2,
      aux_sym_texline_token1,
      anon_sym_BQUOTE,
  [521] = 1,
    ACTIONS(90), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [527] = 1,
    ACTIONS(92), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [533] = 2,
    ACTIONS(96), 1,
      sym__indent,
    ACTIONS(94), 2,
      sym__break,
      ts_builtin_sym_end,
  [541] = 2,
    ACTIONS(100), 1,
      sym__space,
    ACTIONS(98), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [549] = 2,
    ACTIONS(104), 1,
      sym__space,
    ACTIONS(102), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [557] = 1,
    ACTIONS(92), 3,
      sym__indent,
      sym__break,
      ts_builtin_sym_end,
  [563] = 2,
    ACTIONS(108), 1,
      sym__space,
    ACTIONS(106), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [571] = 1,
    ACTIONS(110), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [577] = 2,
    ACTIONS(112), 1,
      sym__indent,
    ACTIONS(94), 2,
      sym__dedent,
      sym__break,
  [585] = 1,
    ACTIONS(114), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [591] = 2,
    ACTIONS(118), 1,
      sym__space,
    ACTIONS(116), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [599] = 1,
    ACTIONS(120), 2,
      sym__dedent,
      sym__break,
  [604] = 2,
    ACTIONS(122), 1,
      sym__dedent,
    ACTIONS(124), 1,
      sym__break,
  [611] = 1,
    ACTIONS(120), 2,
      sym__break,
      ts_builtin_sym_end,
  [616] = 2,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      sym__break,
  [623] = 2,
    ACTIONS(128), 1,
      sym__indent,
    ACTIONS(130), 1,
      sym__break,
  [630] = 1,
    ACTIONS(132), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [635] = 2,
    ACTIONS(134), 1,
      sym__indent,
    STATE(62), 1,
      sym_blockquoted,
  [642] = 2,
    ACTIONS(136), 1,
      sym__indent,
    ACTIONS(138), 1,
      sym__break,
  [649] = 1,
    ACTIONS(110), 1,
      sym__indent,
  [653] = 1,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
  [657] = 1,
    ACTIONS(142), 1,
      sym__dedent,
  [661] = 1,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
  [665] = 1,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
  [669] = 1,
    ACTIONS(148), 1,
      sym__dedent,
  [673] = 1,
    ACTIONS(150), 1,
      sym__dedent,
  [677] = 1,
    ACTIONS(152), 1,
      sym__break,
  [681] = 1,
    ACTIONS(154), 1,
      sym__break,
  [685] = 1,
    ACTIONS(156), 1,
      sym__dedent,
  [689] = 1,
    ACTIONS(90), 1,
      sym__break,
  [693] = 1,
    ACTIONS(158), 1,
      sym__break,
  [697] = 1,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
  [701] = 1,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
  [705] = 1,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
  [709] = 1,
    ACTIONS(164), 1,
      sym__dedent,
  [713] = 1,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
  [717] = 1,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
  [721] = 1,
    ACTIONS(168), 1,
      sym__dedent,
  [725] = 1,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
  [729] = 1,
    ACTIONS(172), 1,
      sym__break,
  [733] = 1,
    ACTIONS(174), 1,
      sym__linefeed,
  [737] = 1,
    ACTIONS(176), 1,
      sym__linefeed,
  [741] = 1,
    ACTIONS(178), 1,
      sym__break,
  [745] = 1,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
  [749] = 1,
    ACTIONS(180), 1,
      sym__dedent,
  [753] = 1,
    ACTIONS(182), 1,
      sym__break,
  [757] = 1,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [761] = 1,
    ACTIONS(186), 1,
      sym__break,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 142,
  [SMALL_STATE(8)] = 168,
  [SMALL_STATE(9)] = 194,
  [SMALL_STATE(10)] = 220,
  [SMALL_STATE(11)] = 243,
  [SMALL_STATE(12)] = 263,
  [SMALL_STATE(13)] = 282,
  [SMALL_STATE(14)] = 301,
  [SMALL_STATE(15)] = 318,
  [SMALL_STATE(16)] = 336,
  [SMALL_STATE(17)] = 354,
  [SMALL_STATE(18)] = 370,
  [SMALL_STATE(19)] = 385,
  [SMALL_STATE(20)] = 399,
  [SMALL_STATE(21)] = 413,
  [SMALL_STATE(22)] = 427,
  [SMALL_STATE(23)] = 436,
  [SMALL_STATE(24)] = 445,
  [SMALL_STATE(25)] = 454,
  [SMALL_STATE(26)] = 463,
  [SMALL_STATE(27)] = 474,
  [SMALL_STATE(28)] = 485,
  [SMALL_STATE(29)] = 494,
  [SMALL_STATE(30)] = 503,
  [SMALL_STATE(31)] = 512,
  [SMALL_STATE(32)] = 521,
  [SMALL_STATE(33)] = 527,
  [SMALL_STATE(34)] = 533,
  [SMALL_STATE(35)] = 541,
  [SMALL_STATE(36)] = 549,
  [SMALL_STATE(37)] = 557,
  [SMALL_STATE(38)] = 563,
  [SMALL_STATE(39)] = 571,
  [SMALL_STATE(40)] = 577,
  [SMALL_STATE(41)] = 585,
  [SMALL_STATE(42)] = 591,
  [SMALL_STATE(43)] = 599,
  [SMALL_STATE(44)] = 604,
  [SMALL_STATE(45)] = 611,
  [SMALL_STATE(46)] = 616,
  [SMALL_STATE(47)] = 623,
  [SMALL_STATE(48)] = 630,
  [SMALL_STATE(49)] = 635,
  [SMALL_STATE(50)] = 642,
  [SMALL_STATE(51)] = 649,
  [SMALL_STATE(52)] = 653,
  [SMALL_STATE(53)] = 657,
  [SMALL_STATE(54)] = 661,
  [SMALL_STATE(55)] = 665,
  [SMALL_STATE(56)] = 669,
  [SMALL_STATE(57)] = 673,
  [SMALL_STATE(58)] = 677,
  [SMALL_STATE(59)] = 681,
  [SMALL_STATE(60)] = 685,
  [SMALL_STATE(61)] = 689,
  [SMALL_STATE(62)] = 693,
  [SMALL_STATE(63)] = 697,
  [SMALL_STATE(64)] = 701,
  [SMALL_STATE(65)] = 705,
  [SMALL_STATE(66)] = 709,
  [SMALL_STATE(67)] = 713,
  [SMALL_STATE(68)] = 717,
  [SMALL_STATE(69)] = 721,
  [SMALL_STATE(70)] = 725,
  [SMALL_STATE(71)] = 729,
  [SMALL_STATE(72)] = 733,
  [SMALL_STATE(73)] = 737,
  [SMALL_STATE(74)] = 741,
  [SMALL_STATE(75)] = 745,
  [SMALL_STATE(76)] = 749,
  [SMALL_STATE(77)] = 753,
  [SMALL_STATE(78)] = 757,
  [SMALL_STATE(79)] = 761,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(15),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(22),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(22),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat1, 2), SHIFT_REPEAT(16),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_blockquoted_repeat1, 2), SHIFT_REPEAT(31),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat1, 2),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat2, 2), SHIFT_REPEAT(27),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat2, 2),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat2, 2), SHIFT_REPEAT(17),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_texdquo, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_texdquo, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__linesplit, 4),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__linesplit, 4),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpol8, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpol8, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpol8, 7),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpol8, 7),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_texline, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_texline, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blockquoted, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exprL, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr2, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr1, 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_linefeed, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat2, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 5),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 5),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply2, 5),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr3, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply1, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply3, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [184] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__break = 2,
  ts_external_token__sentinel = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__break] = sym__break,
  [ts_external_token__sentinel] = sym__sentinel,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
    [ts_external_token__sentinel] = true,
  },
  [2] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
    [ts_external_token__break] = true,
  },
  [4] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
  },
  [5] = {
    [ts_external_token__break] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
  [7] = {
    [ts_external_token__dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_bilang_external_scanner_create(void);
void tree_sitter_bilang_external_scanner_destroy(void *);
bool tree_sitter_bilang_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_bilang_external_scanner_serialize(void *, char *);
void tree_sitter_bilang_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bilang() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_bilang_external_scanner_create,
      tree_sitter_bilang_external_scanner_destroy,
      tree_sitter_bilang_external_scanner_scan,
      tree_sitter_bilang_external_scanner_serialize,
      tree_sitter_bilang_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
