#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_DQUOTE = 1,
  anon_sym_BQUOTE = 2,
  anon_sym_BQUOTE2 = 3,
  anon_sym_BQUOTE_LBRACE = 4,
  anon_sym_RBRACE = 5,
  aux_sym_stx_line_token1 = 6,
  aux_sym_stx_dquo_token1 = 7,
  aux_sym_stx_bloc_token1 = 8,
  aux_sym_stx_word_token1 = 9,
  sym_id = 10,
  sym__space = 11,
  sym__linefeed = 12,
  sym_lparen = 13,
  sym_rparen = 14,
  sym_lbrace = 15,
  sym_lbracket = 16,
  sym_rbracket = 17,
  sym__indent = 18,
  sym__dedent = 19,
  sym__break = 20,
  sym__sentinel = 21,
  sym_program = 22,
  sym__expr3 = 23,
  sym__expr2 = 24,
  sym__expr1 = 25,
  sym__exprL = 26,
  sym_apply3 = 27,
  sym_apply2 = 28,
  sym_apply1 = 29,
  sym__e = 30,
  sym_string = 31,
  sym__stx_words = 32,
  sym__stx_group = 33,
  sym_blockquoted = 34,
  sym_interpol8 = 35,
  sym__codeblock = 36,
  sym_stx_line = 37,
  sym_stx_dquo = 38,
  sym_stx_bloc = 39,
  sym_stx_word = 40,
  sym_linefeed = 41,
  sym__linesplit = 42,
  sym_rbrace = 43,
  aux_sym_string_repeat1 = 44,
  aux_sym_string_repeat2 = 45,
  aux_sym__stx_words_repeat1 = 46,
  aux_sym__stx_group_repeat1 = 47,
  aux_sym_blockquoted_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_BQUOTE2] = "` ",
  [anon_sym_BQUOTE_LBRACE] = "`{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_stx_line_token1] = "stx_line_token1",
  [aux_sym_stx_dquo_token1] = "stx_dquo_token1",
  [aux_sym_stx_bloc_token1] = "stx_bloc_token1",
  [aux_sym_stx_word_token1] = "stx_word_token1",
  [sym_id] = "id",
  [sym__space] = "_space",
  [sym__linefeed] = "_linefeed",
  [sym_lparen] = "lparen",
  [sym_rparen] = "rparen",
  [sym_lbrace] = "lbrace",
  [sym_lbracket] = "lbracket",
  [sym_rbracket] = "rbracket",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__break] = "_break",
  [sym__sentinel] = "_sentinel",
  [sym_program] = "program",
  [sym__expr3] = "_expr3",
  [sym__expr2] = "_expr2",
  [sym__expr1] = "_expr1",
  [sym__exprL] = "_exprL",
  [sym_apply3] = "apply3",
  [sym_apply2] = "apply2",
  [sym_apply1] = "apply1",
  [sym__e] = "_e",
  [sym_string] = "string",
  [sym__stx_words] = "_stx_words",
  [sym__stx_group] = "_stx_group",
  [sym_blockquoted] = "blockquoted",
  [sym_interpol8] = "interpol8",
  [sym__codeblock] = "_codeblock",
  [sym_stx_line] = "stx_line",
  [sym_stx_dquo] = "stx_dquo",
  [sym_stx_bloc] = "stx_bloc",
  [sym_stx_word] = "stx_word",
  [sym_linefeed] = "linefeed",
  [sym__linesplit] = "_linesplit",
  [sym_rbrace] = "rbrace",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym__stx_words_repeat1] = "_stx_words_repeat1",
  [aux_sym__stx_group_repeat1] = "_stx_group_repeat1",
  [aux_sym_blockquoted_repeat1] = "blockquoted_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_BQUOTE2] = anon_sym_BQUOTE2,
  [anon_sym_BQUOTE_LBRACE] = anon_sym_BQUOTE_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_stx_line_token1] = aux_sym_stx_line_token1,
  [aux_sym_stx_dquo_token1] = aux_sym_stx_dquo_token1,
  [aux_sym_stx_bloc_token1] = aux_sym_stx_bloc_token1,
  [aux_sym_stx_word_token1] = aux_sym_stx_word_token1,
  [sym_id] = sym_id,
  [sym__space] = sym__space,
  [sym__linefeed] = sym__linefeed,
  [sym_lparen] = sym_lparen,
  [sym_rparen] = sym_rparen,
  [sym_lbrace] = sym_lbrace,
  [sym_lbracket] = sym_lbracket,
  [sym_rbracket] = sym_rbracket,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__break] = sym__break,
  [sym__sentinel] = sym__sentinel,
  [sym_program] = sym_program,
  [sym__expr3] = sym__expr3,
  [sym__expr2] = sym__expr2,
  [sym__expr1] = sym__expr1,
  [sym__exprL] = sym__exprL,
  [sym_apply3] = sym_apply3,
  [sym_apply2] = sym_apply2,
  [sym_apply1] = sym_apply1,
  [sym__e] = sym__e,
  [sym_string] = sym_string,
  [sym__stx_words] = sym__stx_words,
  [sym__stx_group] = sym__stx_group,
  [sym_blockquoted] = sym_blockquoted,
  [sym_interpol8] = sym_interpol8,
  [sym__codeblock] = sym__codeblock,
  [sym_stx_line] = sym_stx_line,
  [sym_stx_dquo] = sym_stx_dquo,
  [sym_stx_bloc] = sym_stx_bloc,
  [sym_stx_word] = sym_stx_word,
  [sym_linefeed] = sym_linefeed,
  [sym__linesplit] = sym__linesplit,
  [sym_rbrace] = sym_rbrace,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym__stx_words_repeat1] = aux_sym__stx_words_repeat1,
  [aux_sym__stx_group_repeat1] = aux_sym__stx_group_repeat1,
  [aux_sym_blockquoted_repeat1] = aux_sym_blockquoted_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_stx_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stx_dquo_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stx_bloc_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stx_word_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__linefeed] = {
    .visible = false,
    .named = true,
  },
  [sym_lparen] = {
    .visible = true,
    .named = true,
  },
  [sym_rparen] = {
    .visible = true,
    .named = true,
  },
  [sym_lbrace] = {
    .visible = true,
    .named = true,
  },
  [sym_lbracket] = {
    .visible = true,
    .named = true,
  },
  [sym_rbracket] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__break] = {
    .visible = false,
    .named = true,
  },
  [sym__sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__expr3] = {
    .visible = false,
    .named = true,
  },
  [sym__expr2] = {
    .visible = false,
    .named = true,
  },
  [sym__expr1] = {
    .visible = false,
    .named = true,
  },
  [sym__exprL] = {
    .visible = false,
    .named = true,
  },
  [sym_apply3] = {
    .visible = true,
    .named = true,
  },
  [sym_apply2] = {
    .visible = true,
    .named = true,
  },
  [sym_apply1] = {
    .visible = true,
    .named = true,
  },
  [sym__e] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__stx_words] = {
    .visible = false,
    .named = true,
  },
  [sym__stx_group] = {
    .visible = false,
    .named = true,
  },
  [sym_blockquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_interpol8] = {
    .visible = true,
    .named = true,
  },
  [sym__codeblock] = {
    .visible = false,
    .named = true,
  },
  [sym_stx_line] = {
    .visible = true,
    .named = true,
  },
  [sym_stx_dquo] = {
    .visible = true,
    .named = true,
  },
  [sym_stx_bloc] = {
    .visible = true,
    .named = true,
  },
  [sym_stx_word] = {
    .visible = true,
    .named = true,
  },
  [sym_linefeed] = {
    .visible = true,
    .named = true,
  },
  [sym__linesplit] = {
    .visible = false,
    .named = true,
  },
  [sym_rbrace] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__stx_words_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__stx_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blockquoted_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 5,
  [10] = 10,
  [11] = 7,
  [12] = 8,
  [13] = 10,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 15,
  [19] = 16,
  [20] = 17,
  [21] = 14,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 26,
  [27] = 22,
  [28] = 22,
  [29] = 22,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 37,
  [39] = 31,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 44,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 47,
  [50] = 50,
  [51] = 35,
  [52] = 30,
  [53] = 35,
  [54] = 30,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 30,
  [61] = 35,
  [62] = 62,
  [63] = 30,
  [64] = 35,
  [65] = 65,
  [66] = 65,
  [67] = 67,
  [68] = 68,
  [69] = 32,
  [70] = 70,
  [71] = 71,
  [72] = 34,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 74,
  [77] = 77,
  [78] = 33,
  [79] = 70,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 81,
  [84] = 80,
  [85] = 85,
  [86] = 80,
  [87] = 87,
  [88] = 88,
  [89] = 80,
  [90] = 80,
  [91] = 85,
  [92] = 82,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 94,
  [98] = 98,
  [99] = 99,
  [100] = 94,
  [101] = 101,
  [102] = 71,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 94,
  [107] = 103,
  [108] = 108,
  [109] = 103,
  [110] = 94,
  [111] = 103,
  [112] = 112,
  [113] = 103,
  [114] = 114,
  [115] = 105,
  [116] = 101,
  [117] = 95,
  [118] = 108,
  [119] = 77,
  [120] = 96,
  [121] = 112,
  [122] = 122,
  [123] = 123,
  [124] = 98,
};

static inline bool aux_sym_stx_bloc_token1_character_set_1(int32_t c) {
  return (c < '['
    ? (c < '\r'
      ? (c < '\n'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c >= '(' && c <= ')')))
    : (c <= '[' || (c < '{'
      ? (c < '`'
        ? c == ']'
        : c <= '`')
      : (c <= '{' || c == '}'))));
}

static inline bool aux_sym_stx_word_token1_character_set_1(int32_t c) {
  return (c < ','
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '('
        ? c == ' '
        : c <= ')')))
    : (c <= ',' || (c < '`'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '`' || (c < '}'
        ? c == '{'
        : c <= '}')))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '`') ADVANCE(15);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '`') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '`') ADVANCE(13);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '}') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == '`') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BQUOTE2);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BQUOTE_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_stx_line_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_stx_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_stx_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '`') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_stx_dquo_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_stx_dquo_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '`') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_stx_bloc_token1);
      if (!aux_sym_stx_bloc_token1_character_set_1(lookahead)) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_stx_word_token1);
      if (!aux_sym_stx_word_token1_character_set_1(lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_id);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__linefeed);
      if (lookahead == '\t') ADVANCE(30);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_lparen);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_rparen);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_lbrace);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_lbracket);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_rbracket);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 0, .external_lex_state = 3},
  [66] = {.lex_state = 0, .external_lex_state = 3},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 3},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0, .external_lex_state = 3},
  [80] = {.lex_state = 0, .external_lex_state = 3},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0, .external_lex_state = 4},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0, .external_lex_state = 3},
  [85] = {.lex_state = 0, .external_lex_state = 5},
  [86] = {.lex_state = 0, .external_lex_state = 3},
  [87] = {.lex_state = 0, .external_lex_state = 6},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0, .external_lex_state = 3},
  [90] = {.lex_state = 0, .external_lex_state = 3},
  [91] = {.lex_state = 0, .external_lex_state = 4},
  [92] = {.lex_state = 0, .external_lex_state = 5},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0, .external_lex_state = 7},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0, .external_lex_state = 4},
  [99] = {.lex_state = 0, .external_lex_state = 7},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0, .external_lex_state = 6},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0, .external_lex_state = 4},
  [105] = {.lex_state = 0, .external_lex_state = 7},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0, .external_lex_state = 4},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0, .external_lex_state = 7},
  [116] = {.lex_state = 0, .external_lex_state = 7},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0, .external_lex_state = 7},
  [119] = {.lex_state = 0, .external_lex_state = 4},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0, .external_lex_state = 4},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0, .external_lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE2] = ACTIONS(1),
    [anon_sym_BQUOTE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [sym__linefeed] = ACTIONS(1),
    [sym_lparen] = ACTIONS(1),
    [sym_rparen] = ACTIONS(1),
    [sym_lbrace] = ACTIONS(1),
    [sym_lbracket] = ACTIONS(1),
    [sym_rbracket] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__break] = ACTIONS(1),
    [sym__sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(122),
    [sym__expr3] = STATE(120),
    [sym__expr2] = STATE(82),
    [sym__expr1] = STATE(117),
    [sym__exprL] = STATE(79),
    [sym_apply3] = STATE(120),
    [sym_apply2] = STATE(82),
    [sym_apply1] = STATE(117),
    [sym__e] = STATE(81),
    [sym_string] = STATE(81),
    [anon_sym_DQUOTE] = ACTIONS(3),
    [anon_sym_BQUOTE] = ACTIONS(5),
    [anon_sym_BQUOTE2] = ACTIONS(7),
    [sym_id] = ACTIONS(9),
    [sym__linefeed] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    ACTIONS(13), 1,
      sym__linefeed,
    STATE(70), 1,
      sym__exprL,
    STATE(99), 1,
      sym_program,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(92), 2,
      sym__expr2,
      sym_apply2,
    STATE(95), 2,
      sym__expr1,
      sym_apply1,
    STATE(96), 2,
      sym__expr3,
      sym_apply3,
  [38] = 8,
    ACTIONS(15), 1,
      anon_sym_BQUOTE,
    ACTIONS(18), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(23), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(26), 1,
      sym_lparen,
    ACTIONS(29), 1,
      sym_lbrace,
    ACTIONS(32), 1,
      sym_lbracket,
    ACTIONS(21), 3,
      anon_sym_RBRACE,
      sym_rparen,
      sym_rbracket,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [69] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(79), 1,
      sym__exprL,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(82), 2,
      sym__expr2,
      sym_apply2,
    STATE(101), 2,
      sym__expr3,
      sym_apply3,
    STATE(117), 2,
      sym__expr1,
      sym_apply1,
  [101] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(70), 1,
      sym__exprL,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(92), 2,
      sym__expr2,
      sym_apply2,
    STATE(95), 2,
      sym__expr1,
      sym_apply1,
    STATE(118), 2,
      sym__expr3,
      sym_apply3,
  [133] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(70), 1,
      sym__exprL,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(92), 2,
      sym__expr2,
      sym_apply2,
    STATE(95), 2,
      sym__expr1,
      sym_apply1,
    STATE(116), 2,
      sym__expr3,
      sym_apply3,
  [165] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(70), 1,
      sym__exprL,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(92), 2,
      sym__expr2,
      sym_apply2,
    STATE(95), 2,
      sym__expr1,
      sym_apply1,
    STATE(105), 2,
      sym__expr3,
      sym_apply3,
  [197] = 9,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    STATE(32), 1,
      sym_rbrace,
    STATE(10), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [229] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(79), 1,
      sym__exprL,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(82), 2,
      sym__expr2,
      sym_apply2,
    STATE(108), 2,
      sym__expr3,
      sym_apply3,
    STATE(117), 2,
      sym__expr1,
      sym_apply1,
  [261] = 9,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    STATE(33), 1,
      sym_rbrace,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [293] = 9,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(70), 1,
      sym__exprL,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(92), 2,
      sym__expr2,
      sym_apply2,
    STATE(95), 2,
      sym__expr1,
      sym_apply1,
    STATE(115), 2,
      sym__expr3,
      sym_apply3,
  [325] = 9,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_rbrace,
    STATE(13), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [357] = 9,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_rbrace,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [389] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(51), 1,
      sym_rbracket,
    STATE(16), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [418] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(53), 1,
      sym_rparen,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [447] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(55), 1,
      sym_rbracket,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [476] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(51), 1,
      sym_rparen,
    STATE(18), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [505] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(55), 1,
      sym_rparen,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [534] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(53), 1,
      sym_rbracket,
    STATE(3), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [563] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(57), 1,
      sym_rparen,
    STATE(15), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [592] = 8,
    ACTIONS(35), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(41), 1,
      aux_sym_stx_bloc_token1,
    ACTIONS(43), 1,
      sym_lparen,
    ACTIONS(45), 1,
      sym_lbrace,
    ACTIONS(47), 1,
      sym_lbracket,
    ACTIONS(57), 1,
      sym_rbracket,
    STATE(19), 5,
      sym__stx_group,
      sym_interpol8,
      sym_stx_bloc,
      sym__linesplit,
      aux_sym__stx_group_repeat1,
  [621] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      anon_sym_BQUOTE2,
    ACTIONS(61), 1,
      sym_id,
    ACTIONS(63), 1,
      sym__linefeed,
    STATE(83), 2,
      sym__e,
      sym_string,
    STATE(106), 3,
      sym__expr1,
      sym_apply1,
      sym__codeblock,
  [646] = 6,
    ACTIONS(65), 1,
      anon_sym_BQUOTE,
    ACTIONS(67), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(71), 1,
      aux_sym_stx_word_token1,
    ACTIONS(73), 1,
      sym__space,
    ACTIONS(69), 2,
      anon_sym_RBRACE,
      sym__linefeed,
    STATE(26), 4,
      sym_interpol8,
      sym_stx_word,
      sym__linesplit,
      aux_sym__stx_words_repeat1,
  [669] = 6,
    ACTIONS(75), 1,
      anon_sym_DQUOTE,
    ACTIONS(79), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(81), 1,
      sym__linefeed,
    STATE(87), 1,
      sym_linefeed,
    ACTIONS(77), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_dquo_token1,
    STATE(41), 4,
      sym_interpol8,
      sym_stx_dquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [692] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      anon_sym_BQUOTE2,
    ACTIONS(61), 1,
      sym_id,
    ACTIONS(83), 1,
      sym__linefeed,
    STATE(83), 2,
      sym__e,
      sym_string,
    STATE(97), 3,
      sym__expr1,
      sym_apply1,
      sym__codeblock,
  [717] = 6,
    ACTIONS(85), 1,
      anon_sym_BQUOTE,
    ACTIONS(88), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(93), 1,
      aux_sym_stx_word_token1,
    ACTIONS(96), 1,
      sym__space,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      sym__linefeed,
    STATE(26), 4,
      sym_interpol8,
      sym_stx_word,
      sym__linesplit,
      aux_sym__stx_words_repeat1,
  [740] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      anon_sym_BQUOTE2,
    ACTIONS(61), 1,
      sym_id,
    ACTIONS(98), 1,
      sym__linefeed,
    STATE(83), 2,
      sym__e,
      sym_string,
    STATE(100), 3,
      sym__expr1,
      sym_apply1,
      sym__codeblock,
  [765] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      anon_sym_BQUOTE2,
    ACTIONS(61), 1,
      sym_id,
    ACTIONS(100), 1,
      sym__linefeed,
    STATE(83), 2,
      sym__e,
      sym_string,
    STATE(94), 3,
      sym__expr1,
      sym_apply1,
      sym__codeblock,
  [790] = 7,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      anon_sym_BQUOTE2,
    ACTIONS(61), 1,
      sym_id,
    ACTIONS(102), 1,
      sym__linefeed,
    STATE(83), 2,
      sym__e,
      sym_string,
    STATE(110), 3,
      sym__expr1,
      sym_apply1,
      sym__codeblock,
  [815] = 2,
    ACTIONS(104), 1,
      anon_sym_BQUOTE,
    ACTIONS(106), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [829] = 5,
    ACTIONS(111), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(114), 1,
      sym__space,
    ACTIONS(116), 1,
      sym__linefeed,
    ACTIONS(108), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(31), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [849] = 2,
    ACTIONS(118), 1,
      anon_sym_BQUOTE,
    ACTIONS(120), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [863] = 2,
    ACTIONS(122), 1,
      anon_sym_BQUOTE,
    ACTIONS(124), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [877] = 2,
    ACTIONS(126), 1,
      anon_sym_BQUOTE,
    ACTIONS(128), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [891] = 2,
    ACTIONS(130), 1,
      anon_sym_BQUOTE,
    ACTIONS(132), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [905] = 2,
    ACTIONS(134), 1,
      anon_sym_BQUOTE,
    ACTIONS(136), 8,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_bloc_token1,
      sym_lparen,
      sym_rparen,
      sym_lbrace,
      sym_lbracket,
      sym_rbracket,
  [919] = 4,
    ACTIONS(140), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(138), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    ACTIONS(142), 2,
      anon_sym_RBRACE,
      sym__space,
    STATE(39), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [937] = 5,
    ACTIONS(142), 1,
      sym__space,
    ACTIONS(146), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(148), 1,
      sym__linefeed,
    ACTIONS(144), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(31), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [957] = 4,
    ACTIONS(153), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(114), 2,
      anon_sym_RBRACE,
      sym__space,
    ACTIONS(150), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(39), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [975] = 5,
    ACTIONS(146), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(156), 1,
      sym__linefeed,
    STATE(75), 1,
      sym_linefeed,
    ACTIONS(144), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
    STATE(31), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [995] = 5,
    ACTIONS(77), 1,
      anon_sym_BQUOTE,
    ACTIONS(79), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(158), 1,
      anon_sym_DQUOTE,
    ACTIONS(160), 1,
      aux_sym_stx_dquo_token1,
    STATE(43), 4,
      sym_interpol8,
      sym_stx_dquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [1014] = 6,
    ACTIONS(162), 1,
      sym_lparen,
    ACTIONS(164), 1,
      sym_lbrace,
    ACTIONS(166), 1,
      sym_lbracket,
    STATE(46), 1,
      sym_stx_word,
    ACTIONS(71), 2,
      anon_sym_BQUOTE,
      aux_sym_stx_word_token1,
    STATE(68), 2,
      sym__stx_words,
      sym__stx_group,
  [1035] = 5,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      anon_sym_BQUOTE,
    ACTIONS(173), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(176), 1,
      aux_sym_stx_dquo_token1,
    STATE(43), 4,
      sym_interpol8,
      sym_stx_dquo,
      sym__linesplit,
      aux_sym_string_repeat1,
  [1054] = 6,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_BQUOTE2,
    ACTIONS(9), 1,
      sym_id,
    STATE(81), 2,
      sym__e,
      sym_string,
    STATE(88), 2,
      sym__expr1,
      sym_apply1,
  [1075] = 6,
    ACTIONS(3), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 1,
      anon_sym_BQUOTE,
    ACTIONS(59), 1,
      anon_sym_BQUOTE2,
    ACTIONS(61), 1,
      sym_id,
    STATE(83), 2,
      sym__e,
      sym_string,
    STATE(88), 2,
      sym__expr1,
      sym_apply1,
  [1096] = 4,
    ACTIONS(65), 1,
      anon_sym_BQUOTE,
    ACTIONS(67), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(71), 1,
      aux_sym_stx_word_token1,
    STATE(23), 4,
      sym_interpol8,
      sym_stx_word,
      sym__linesplit,
      aux_sym__stx_words_repeat1,
  [1112] = 4,
    ACTIONS(144), 1,
      anon_sym_BQUOTE,
    ACTIONS(146), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(179), 1,
      aux_sym_stx_line_token1,
    STATE(38), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [1128] = 4,
    ACTIONS(144), 1,
      anon_sym_BQUOTE,
    ACTIONS(146), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(179), 1,
      aux_sym_stx_line_token1,
    STATE(40), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [1144] = 4,
    ACTIONS(138), 1,
      anon_sym_BQUOTE,
    ACTIONS(140), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(181), 1,
      aux_sym_stx_line_token1,
    STATE(37), 4,
      sym_interpol8,
      sym_stx_line,
      sym__linesplit,
      aux_sym_string_repeat2,
  [1160] = 2,
    ACTIONS(183), 2,
      anon_sym_BQUOTE,
      sym__space,
    ACTIONS(185), 4,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_word_token1,
      sym__linefeed,
  [1171] = 2,
    ACTIONS(130), 2,
      anon_sym_BQUOTE,
      sym__space,
    ACTIONS(132), 4,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_word_token1,
      sym__linefeed,
  [1182] = 2,
    ACTIONS(104), 2,
      anon_sym_BQUOTE,
      sym__space,
    ACTIONS(106), 4,
      anon_sym_BQUOTE_LBRACE,
      anon_sym_RBRACE,
      aux_sym_stx_word_token1,
      sym__linefeed,
  [1193] = 2,
    ACTIONS(132), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(130), 3,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
      sym__space,
  [1203] = 2,
    ACTIONS(106), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(104), 3,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
      sym__space,
  [1213] = 4,
    ACTIONS(187), 1,
      sym__indent,
    ACTIONS(189), 1,
      sym__dedent,
    ACTIONS(191), 1,
      sym__break,
    STATE(57), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1227] = 4,
    ACTIONS(187), 1,
      sym__indent,
    ACTIONS(191), 1,
      sym__break,
    ACTIONS(193), 1,
      sym__dedent,
    STATE(57), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1241] = 4,
    ACTIONS(195), 1,
      sym__indent,
    ACTIONS(198), 1,
      sym__dedent,
    ACTIONS(200), 1,
      sym__break,
    STATE(57), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1255] = 2,
    ACTIONS(205), 2,
      anon_sym_BQUOTE_LBRACE,
      sym__linefeed,
    ACTIONS(203), 3,
      anon_sym_BQUOTE,
      aux_sym_stx_line_token1,
      sym__space,
  [1265] = 2,
    ACTIONS(205), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(203), 4,
      anon_sym_BQUOTE,
      anon_sym_RBRACE,
      aux_sym_stx_line_token1,
      sym__space,
  [1275] = 2,
    ACTIONS(106), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(104), 4,
      anon_sym_BQUOTE,
      anon_sym_RBRACE,
      aux_sym_stx_line_token1,
      sym__space,
  [1285] = 2,
    ACTIONS(132), 1,
      anon_sym_BQUOTE_LBRACE,
    ACTIONS(130), 4,
      anon_sym_BQUOTE,
      anon_sym_RBRACE,
      aux_sym_stx_line_token1,
      sym__space,
  [1295] = 2,
    ACTIONS(209), 1,
      anon_sym_BQUOTE,
    ACTIONS(207), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_stx_dquo_token1,
  [1304] = 2,
    ACTIONS(104), 1,
      anon_sym_BQUOTE,
    ACTIONS(106), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_stx_dquo_token1,
  [1313] = 2,
    ACTIONS(130), 1,
      anon_sym_BQUOTE,
    ACTIONS(132), 3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_LBRACE,
      aux_sym_stx_dquo_token1,
  [1322] = 3,
    ACTIONS(187), 1,
      sym__indent,
    ACTIONS(191), 1,
      sym__break,
    STATE(55), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1333] = 3,
    ACTIONS(187), 1,
      sym__indent,
    ACTIONS(191), 1,
      sym__break,
    STATE(56), 2,
      sym_blockquoted,
      aux_sym_blockquoted_repeat1,
  [1344] = 2,
    ACTIONS(213), 1,
      sym__space,
    ACTIONS(211), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1352] = 2,
    ACTIONS(142), 1,
      sym__space,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1360] = 2,
    ACTIONS(118), 1,
      sym__space,
    ACTIONS(120), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1368] = 2,
    ACTIONS(215), 1,
      sym__indent,
    ACTIONS(217), 2,
      sym__dedent,
      sym__break,
  [1376] = 1,
    ACTIONS(219), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [1382] = 2,
    ACTIONS(126), 1,
      sym__space,
    ACTIONS(128), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1390] = 2,
    ACTIONS(223), 1,
      sym__space,
    ACTIONS(221), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1398] = 1,
    ACTIONS(225), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [1404] = 1,
    ACTIONS(227), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [1410] = 1,
    ACTIONS(225), 3,
      sym__indent,
      sym__break,
      ts_builtin_sym_end,
  [1416] = 1,
    ACTIONS(229), 3,
      sym__indent,
      sym__dedent,
      sym__break,
  [1422] = 2,
    ACTIONS(122), 1,
      sym__space,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1430] = 2,
    ACTIONS(231), 1,
      sym__indent,
    ACTIONS(217), 2,
      sym__break,
      ts_builtin_sym_end,
  [1438] = 2,
    ACTIONS(233), 1,
      sym__indent,
    ACTIONS(235), 1,
      sym__break,
  [1445] = 2,
    ACTIONS(237), 1,
      sym__space,
    ACTIONS(239), 1,
      sym__linefeed,
  [1452] = 2,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
    ACTIONS(243), 1,
      sym__break,
  [1459] = 2,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
    ACTIONS(245), 1,
      sym__space,
  [1466] = 2,
    ACTIONS(233), 1,
      sym__indent,
    ACTIONS(247), 1,
      sym__break,
  [1473] = 1,
    ACTIONS(249), 2,
      sym__dedent,
      sym__break,
  [1478] = 2,
    ACTIONS(233), 1,
      sym__indent,
    ACTIONS(251), 1,
      sym__break,
  [1485] = 2,
    ACTIONS(253), 1,
      sym__indent,
    STATE(93), 1,
      sym_blockquoted,
  [1492] = 1,
    ACTIONS(255), 2,
      anon_sym_RBRACE,
      sym__linefeed,
  [1497] = 2,
    ACTIONS(233), 1,
      sym__indent,
    ACTIONS(257), 1,
      sym__break,
  [1504] = 2,
    ACTIONS(233), 1,
      sym__indent,
    ACTIONS(259), 1,
      sym__break,
  [1511] = 1,
    ACTIONS(249), 2,
      sym__break,
      ts_builtin_sym_end,
  [1516] = 2,
    ACTIONS(241), 1,
      sym__dedent,
    ACTIONS(261), 1,
      sym__break,
  [1523] = 1,
    ACTIONS(263), 1,
      sym__break,
  [1527] = 1,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
  [1531] = 1,
    ACTIONS(267), 1,
      sym__linefeed,
  [1535] = 1,
    ACTIONS(269), 1,
      sym__dedent,
  [1539] = 1,
    ACTIONS(271), 1,
      anon_sym_RBRACE,
  [1543] = 1,
    ACTIONS(273), 1,
      sym__break,
  [1547] = 1,
    ACTIONS(275), 1,
      sym__dedent,
  [1551] = 1,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
  [1555] = 1,
    ACTIONS(279), 1,
      ts_builtin_sym_end,
  [1559] = 1,
    ACTIONS(219), 1,
      sym__indent,
  [1563] = 1,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
  [1567] = 1,
    ACTIONS(283), 1,
      sym__break,
  [1571] = 1,
    ACTIONS(285), 1,
      sym__dedent,
  [1575] = 1,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
  [1579] = 1,
    ACTIONS(289), 1,
      anon_sym_RBRACE,
  [1583] = 1,
    ACTIONS(291), 1,
      ts_builtin_sym_end,
  [1587] = 1,
    ACTIONS(293), 1,
      anon_sym_RBRACE,
  [1591] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
  [1595] = 1,
    ACTIONS(297), 1,
      anon_sym_RBRACE,
  [1599] = 1,
    ACTIONS(299), 1,
      sym__break,
  [1603] = 1,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
  [1607] = 1,
    ACTIONS(303), 1,
      anon_sym_DQUOTE,
  [1611] = 1,
    ACTIONS(305), 1,
      sym__dedent,
  [1615] = 1,
    ACTIONS(279), 1,
      sym__dedent,
  [1619] = 1,
    ACTIONS(307), 1,
      sym__linefeed,
  [1623] = 1,
    ACTIONS(291), 1,
      sym__dedent,
  [1627] = 1,
    ACTIONS(229), 1,
      sym__break,
  [1631] = 1,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
  [1635] = 1,
    ACTIONS(309), 1,
      sym__break,
  [1639] = 1,
    ACTIONS(311), 1,
      ts_builtin_sym_end,
  [1643] = 1,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
  [1647] = 1,
    ACTIONS(315), 1,
      sym__break,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 69,
  [SMALL_STATE(5)] = 101,
  [SMALL_STATE(6)] = 133,
  [SMALL_STATE(7)] = 165,
  [SMALL_STATE(8)] = 197,
  [SMALL_STATE(9)] = 229,
  [SMALL_STATE(10)] = 261,
  [SMALL_STATE(11)] = 293,
  [SMALL_STATE(12)] = 325,
  [SMALL_STATE(13)] = 357,
  [SMALL_STATE(14)] = 389,
  [SMALL_STATE(15)] = 418,
  [SMALL_STATE(16)] = 447,
  [SMALL_STATE(17)] = 476,
  [SMALL_STATE(18)] = 505,
  [SMALL_STATE(19)] = 534,
  [SMALL_STATE(20)] = 563,
  [SMALL_STATE(21)] = 592,
  [SMALL_STATE(22)] = 621,
  [SMALL_STATE(23)] = 646,
  [SMALL_STATE(24)] = 669,
  [SMALL_STATE(25)] = 692,
  [SMALL_STATE(26)] = 717,
  [SMALL_STATE(27)] = 740,
  [SMALL_STATE(28)] = 765,
  [SMALL_STATE(29)] = 790,
  [SMALL_STATE(30)] = 815,
  [SMALL_STATE(31)] = 829,
  [SMALL_STATE(32)] = 849,
  [SMALL_STATE(33)] = 863,
  [SMALL_STATE(34)] = 877,
  [SMALL_STATE(35)] = 891,
  [SMALL_STATE(36)] = 905,
  [SMALL_STATE(37)] = 919,
  [SMALL_STATE(38)] = 937,
  [SMALL_STATE(39)] = 957,
  [SMALL_STATE(40)] = 975,
  [SMALL_STATE(41)] = 995,
  [SMALL_STATE(42)] = 1014,
  [SMALL_STATE(43)] = 1035,
  [SMALL_STATE(44)] = 1054,
  [SMALL_STATE(45)] = 1075,
  [SMALL_STATE(46)] = 1096,
  [SMALL_STATE(47)] = 1112,
  [SMALL_STATE(48)] = 1128,
  [SMALL_STATE(49)] = 1144,
  [SMALL_STATE(50)] = 1160,
  [SMALL_STATE(51)] = 1171,
  [SMALL_STATE(52)] = 1182,
  [SMALL_STATE(53)] = 1193,
  [SMALL_STATE(54)] = 1203,
  [SMALL_STATE(55)] = 1213,
  [SMALL_STATE(56)] = 1227,
  [SMALL_STATE(57)] = 1241,
  [SMALL_STATE(58)] = 1255,
  [SMALL_STATE(59)] = 1265,
  [SMALL_STATE(60)] = 1275,
  [SMALL_STATE(61)] = 1285,
  [SMALL_STATE(62)] = 1295,
  [SMALL_STATE(63)] = 1304,
  [SMALL_STATE(64)] = 1313,
  [SMALL_STATE(65)] = 1322,
  [SMALL_STATE(66)] = 1333,
  [SMALL_STATE(67)] = 1344,
  [SMALL_STATE(68)] = 1352,
  [SMALL_STATE(69)] = 1360,
  [SMALL_STATE(70)] = 1368,
  [SMALL_STATE(71)] = 1376,
  [SMALL_STATE(72)] = 1382,
  [SMALL_STATE(73)] = 1390,
  [SMALL_STATE(74)] = 1398,
  [SMALL_STATE(75)] = 1404,
  [SMALL_STATE(76)] = 1410,
  [SMALL_STATE(77)] = 1416,
  [SMALL_STATE(78)] = 1422,
  [SMALL_STATE(79)] = 1430,
  [SMALL_STATE(80)] = 1438,
  [SMALL_STATE(81)] = 1445,
  [SMALL_STATE(82)] = 1452,
  [SMALL_STATE(83)] = 1459,
  [SMALL_STATE(84)] = 1466,
  [SMALL_STATE(85)] = 1473,
  [SMALL_STATE(86)] = 1478,
  [SMALL_STATE(87)] = 1485,
  [SMALL_STATE(88)] = 1492,
  [SMALL_STATE(89)] = 1497,
  [SMALL_STATE(90)] = 1504,
  [SMALL_STATE(91)] = 1511,
  [SMALL_STATE(92)] = 1516,
  [SMALL_STATE(93)] = 1523,
  [SMALL_STATE(94)] = 1527,
  [SMALL_STATE(95)] = 1531,
  [SMALL_STATE(96)] = 1535,
  [SMALL_STATE(97)] = 1539,
  [SMALL_STATE(98)] = 1543,
  [SMALL_STATE(99)] = 1547,
  [SMALL_STATE(100)] = 1551,
  [SMALL_STATE(101)] = 1555,
  [SMALL_STATE(102)] = 1559,
  [SMALL_STATE(103)] = 1563,
  [SMALL_STATE(104)] = 1567,
  [SMALL_STATE(105)] = 1571,
  [SMALL_STATE(106)] = 1575,
  [SMALL_STATE(107)] = 1579,
  [SMALL_STATE(108)] = 1583,
  [SMALL_STATE(109)] = 1587,
  [SMALL_STATE(110)] = 1591,
  [SMALL_STATE(111)] = 1595,
  [SMALL_STATE(112)] = 1599,
  [SMALL_STATE(113)] = 1603,
  [SMALL_STATE(114)] = 1607,
  [SMALL_STATE(115)] = 1611,
  [SMALL_STATE(116)] = 1615,
  [SMALL_STATE(117)] = 1619,
  [SMALL_STATE(118)] = 1623,
  [SMALL_STATE(119)] = 1627,
  [SMALL_STATE(120)] = 1631,
  [SMALL_STATE(121)] = 1635,
  [SMALL_STATE(122)] = 1639,
  [SMALL_STATE(123)] = 1643,
  [SMALL_STATE(124)] = 1647,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stx_group_repeat1, 2), SHIFT_REPEAT(36),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stx_group_repeat1, 2), SHIFT_REPEAT(22),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__stx_group_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stx_group_repeat1, 2), SHIFT_REPEAT(36),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stx_group_repeat1, 2), SHIFT_REPEAT(17),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stx_group_repeat1, 2), SHIFT_REPEAT(8),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stx_group_repeat1, 2), SHIFT_REPEAT(14),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stx_words, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stx_words, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__stx_words_repeat1, 2), SHIFT_REPEAT(50),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stx_words_repeat1, 2), SHIFT_REPEAT(28),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__stx_words_repeat1, 2),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__stx_words_repeat1, 2), SHIFT_REPEAT(50),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__stx_words_repeat1, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpol8, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpol8, 3),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(58),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(27),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stx_group, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stx_group, 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stx_group, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stx_group, 3),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rbrace, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rbrace, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__linesplit, 4),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__linesplit, 4),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stx_bloc, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stx_bloc, 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(59),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(29),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(62),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(25),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(62),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stx_word, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stx_word, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat1, 2), SHIFT_REPEAT(66),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat1, 2),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat1, 2), SHIFT_REPEAT(48),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stx_line, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stx_line, 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stx_dquo, 1),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stx_dquo, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 5),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 5),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr2, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_linefeed, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exprL, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_blockquoted_repeat1, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blockquoted, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr1, 1),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr3, 1),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply2, 5),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply1, 3),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply3, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [311] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__codeblock, 5),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__break = 2,
  ts_external_token__sentinel = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__break] = sym__break,
  [ts_external_token__sentinel] = sym__sentinel,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
    [ts_external_token__sentinel] = true,
  },
  [2] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
    [ts_external_token__break] = true,
  },
  [4] = {
    [ts_external_token__break] = true,
  },
  [5] = {
    [ts_external_token__dedent] = true,
    [ts_external_token__break] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
  [7] = {
    [ts_external_token__dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_bilang_external_scanner_create(void);
void tree_sitter_bilang_external_scanner_destroy(void *);
bool tree_sitter_bilang_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_bilang_external_scanner_serialize(void *, char *);
void tree_sitter_bilang_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bilang() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_bilang_external_scanner_create,
      tree_sitter_bilang_external_scanner_destroy,
      tree_sitter_bilang_external_scanner_scan,
      tree_sitter_bilang_external_scanner_serialize,
      tree_sitter_bilang_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
